spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://nyseenow.cbqpbir87k5q.eu-west-1.rds.amazonaws.com:5432/UserAccount
    username: fei
    password: 22200125
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      connection:
        provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl.auto: update
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
